version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  "build":
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:17.0.13
    steps:
      - checkout
      - run:
          name: mvn-test
          command: mvn test
      - run:
          name: mvn-install
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - persist_to_workspace:
          root: ./
          paths: target
  "build_and_release":
    working_directory: ~/repo
    docker:
      - image: cimg/base:2025.04
    steps:
      - run:
          name: docker-deploy
          command: sh ./scripts/docker_release.sh