version: 2.1

executors:
  ws-executor:
    working_directory: /tmp

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - build_and_release:
          context:
            - docker
          requires:
            - build

jobs:
  "build":
    executor: ws-executor
    docker:
      - image: cimg/openjdk:17.0.13
    steps:
      - run: mkdir -p workspace
      - checkout:
          path: workspace
      - run: cd workspace
      - run:
          name: mvn-test
          command: mvn test
          working_directory: workspace
      - run:
          name: mvn-install
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          working_directory: workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - target
            - scripts
            - Dockerfile
  "build_and_release":
    executor: ws-executor
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
            at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: docker-deploy
          command: sh ./scripts/docker-build.sh
          working_directory: workspace
